jritchie-portfolio/Models/EmailModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace jritchie_portfolio.Models
{
    public class EmailModel
    {
        [Required, Display(Name = "Name")]                      // Displays 'Name' instead of property's name.
        public string FromName { get; set; }
        [Required, Display(Name = "Email"), EmailAddress]       // Validates email address.
        public string FromEmail { get; set; }
        public string Subject { get; set; }                     // Remove [Required] attribute to allow HomeController's Contact Action to generate Subject line.
        [Required]
        public string Body { get; set; }
    }
}

jritchie-portfolio/Controllers/HomeController.cs
using jritchie_portfolio.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace jritchie_portfolio.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Contact(EmailModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var body = "<p>Email From: <bold>{0}</bold>({1})</p><p>Message:</p><p>{2}</p>";
                    var from = "MyPortfolio<jritchie.nc@gmail.com>";
                    //model.Body = "This is a message from your portfolio site.  The name and the email of the contacting person is above.";
                    string subject = null;
                    if (model.Subject != null)
                    {
                        subject = "Portfolio Contact Email: " + model.Subject;
                    }
                    else
                    {
                        subject = "Portfolio Contact Email";
                    }


                    var email = new MailMessage(from, ConfigurationManager.AppSettings["emailto"])
                    {
                        //Subject = "Portfolio Contact Email" + model.Subject,
                        Subject = subject,
                        Body = string.Format(body, model.FromName, model.FromEmail, model.Body),
                        IsBodyHtml = true
                    };

                    var svc = new PersonalEmail();
                    await svc.SendAsync(email);             // Sends email.

                    return View(new EmailModel());          // Return to View (need to send empty Email model)
                    //return RedirectToAction("Sent");
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    await Task.FromResult(0);
                }
            }
            return View(model);
        }

        public ActionResult Portfolio()
        {
            return View();
        }

        public ActionResult TabPrinter()
        {
            return View();
        }

        public ActionResult GTCCCapstone()
        {
            return View();
        }

        public ActionResult Resume()
        {
            return View();
        }

        public FileResult JRitchieResume(string filename)
        {
            return File(filename, "application/pdf");
        }
    }
}

jritchie-portfolio/Controllers/JsExercisesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace jritchie_portfolio.Controllers
{
    public class JsExercisesController : Controller
    {
        // GET: JsExercises
        public ActionResult Index()
        {
            return View();
        }
    }
}

jritchie-portfolio/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}


<section id="about">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <h2 class="section-heading" style="text-shadow:2px 2px 3px rgba(30,30,30,0.25)">My background</h2>
                <hr class="blue" />
                <p>While a student at UNC-Charlotte, a summer internship allowed me to explore database development using dBase III.</p>
                <p>This experience led to my subsequent employment at the Bryan School of Business & Economics at UNC-Greensboro, where I developed databases to handle the school's internal financial recordkeeping and billing.</p>
                <p>Several years later, I discovered Object-Oriented programming through VBA in Excel. Eventually, however, my projects needed more power and flexibility than VBA allowed, and I began teaching myself VB.NET.</p>
                <p><a href="@Url.Action("TabPrinter", "Home")" style="font-style:italic">Tab Printer</a>, my first VB.NET application, was used in production by the school's print shop for flexible, full-color, high speed printing of 3-ring binder index tabs.</p>
                <p>The success of <a href="@Url.Action("TabPrinter", "Home")" style="font-style:italic">Tab Printer</a> led to the development of front-ends for several Microsoft Access databases.</p>
                <p>After leaving UNC-Greensboro, I spent time exploring computer graphics and animation before returning to programming. I enrolled at Guilford Technical Community College to bring my skills up-to-date, and to help 'fill-in' the gaps in my self-taught skillset.</p>
                <p>Coder Foundry is the next step in my growth as a developer.</p>
                <p>When not writing code, I enjoy reading, writing, and photography. Some of my pictures are shown below.</p>
            </div>
        </div>
    </div>

    <div class="container-fluid" style="width:80%">
        <div class="row no-gutter popup-gallery">
            <!-- Beach -->
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a class="aboutPortfolio-box" href="~/Assets/img/portfolio/fullsize/IMG_0047.JPG">
                    <img class="img-fluid" src="~/Assets/img/portfolio/thumbnails/IMG_0047.JPG" alt="">
                </a>
            </div>
            <!-- Sunrise -->
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a class="aboutPortfolio-box" href="~/Assets/img/portfolio/fullsize/IMG_0059.JPG">
                    <img class="img-fluid" src="~/Assets/img/portfolio/thumbnails/IMG_0059.JPG" alt="">
                </a>
            </div>
            <!-- Mushrooms in field -->
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a class="aboutPortfolio-box" href="~/Assets/img/portfolio/fullsize/IMG_0469.JPG">
                    <img class="img-fluid" src="~/Assets/img/portfolio/thumbnails/IMG_0469.JPG" alt="">
                </a>
            </div>
            <!-- Flower -->
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a class="aboutPortfolio-box" href="~/Assets/img/portfolio/fullsize/IMG_1842.JPG">
                    <img class="img-fluid" src="~/Assets/img/portfolio/thumbnails/IMG_1842.JPG" alt="">
                </a>
            </div>
            <!-- Hummingbird -->
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a class="aboutPortfolio-box" href="~/Assets/img/portfolio/fullsize/IMG_1591.JPG">
                    <img class="img-fluid" src="~/Assets/img/portfolio/thumbnails/IMG_1591.JPG" alt="">
                </a>
            </div>
            <!-- Dog -->
            <div class="col-lg-4 col-md-4 col-sm-6">
                <a class="aboutPortfolio-box" href="~/Assets/img/portfolio/fullsize/IMG_2216.JPG">
                    <img class="img-fluid" src="~/Assets/img/portfolio/thumbnails/IMG_2216.JPG" alt="">
                </a>
            </div>

        </div>
    </div>

</section>

jritchie-portfolio/Views/Home/Contact.cshtml
@model jritchie_portfolio.Models.EmailModel

@{
    ViewBag.Title = "Contact";
}


<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mx-auto text-center">
                <h2 class="section-heading" style="text-shadow:2px 2px 3px rgba(30,30,30,0.25)">Get In Touch</h2>
                <hr class="blue">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 ml-auto text-center">
                <a href="https://www.linkedin.com/in/john-ritchie-49bba0149/" >
                    <div class="javascript-box">
                        <img class="sr-contact" src="~/Assets/img/Logo-2C-34px-R.png" style="margin-top:5px" />
                        <p class="text-muted" style="margin-top:3px">
                        Find me on LinkedIn.
                        </p>
                    </div>
                </a>
            </div>
            <div class="col-lg-6 mr-auto text-center">
                <a href="mailto:jritchie.nc@gmail.com">
                    <div class="javascript-box">
                        <i class="fa fa-envelope fa-3x sr-contact"></i>
                        <p class="text-muted">
                            jritchie.nc@gmail.com
                        </p>
                    </div>
                </a>

                <hr class="blue" style="margin-bottom:40px !important"/>

                <h4>Send a message.</h4>

                @using (Html.BeginForm())                   // Creates <form method="Post" action="Home/Contact"
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary("", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(m => m.FromName, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.FromName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.FromName)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.FromEmail, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.FromEmail, new { @class = "form-control", placeholder = "example@email.com" })
                            @Html.ValidationMessageFor(m => m.FromEmail)
                        </div>
                    </div>

                    <!-- Email Subject. -->
                    <div class="form-group">
                        @Html.LabelFor(m => m.Subject, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Subject, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Subject)
                        </div>
                    </div>

                    <!-- Email Body -->
                    <div class="form-group">
                        @Html.Label("Message", new { @class = "col-md-2 control-label" })
                        @*@Html.LabelFor(m => m.Body, new { @class = "col-md-2 control-label" })*@
                        <div class="col-md-10">
                            <textarea rows="5" name="Body" style="max-width:none !important; width:100%"></textarea>
                            @*@Html.TextBoxFor(m => m.Body, new { @class = "form-control" })*@
                            @Html.ValidationMessageFor(m => m.Body)
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12" style="margin-top:20px">
                            <input type="submit" class="btn btn-primary" value="Send" />
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</section>

jritchie-portfolio/Views/Home/GTCCCapstone.cshtml
@{
    ViewBag.Title = "GTCC Capstone";
}


<!-- GTCC Capstone -->
<section id="GTCCCapstone">
    <div class="container">

        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">

                <h2 class="section-heading" style="text-shadow:2px 2px 3px rgba(30,30,30,0.25)">GTCC Programming Capstone course</h2>
                <hr class="blue" />

                <p>The Programming Capstone course is a semester-long, on-line course with minimal instructor involvement. This course is the last course taken before graduation.</p>
                <p style="margin-bottom:0px">The course is designed to replicate real-world business analysis and programming techniques, and begins with an introduction to a (fictitious) business, which includes interviews with key employees and samples of paper forms the business uses.</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <div style="padding:10px; border:2px solid #009999; background-color:rgba(0,153,153,0.05)">
                    <table id="capstoneTable" class="table-striped table-hover" style="width:100%">
                        <thead>
                            <tr><th></th></tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/Unit1ProjectIntroduction.pdf">Capstone Project Introduction</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>



        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <p style="margin-top:40px; margin-bottom:0px" >A SWOT (Strengths, Weaknesses, Opportunities, & Threats) analysis is performed to ensure the company's needs are understood. Next, database design is considered through the creation of an Entity Relationship Diagram (ERD).</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div style="padding:10px; border:2px solid #009999; background-color:rgba(0,153,153,0.05)">
                    <table id="capstoneTable" class="table-striped table-hover" style="width:100%">
                        <thead>
                            <tr>
                                <th style="padding:6px !important">
                                    Instructions
                                </th>
                                <th style="padding:6px !important">
                                    Resulting Analysis
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/Unit2RequirementsSWOTAnalysis.pdf">SWOT Analysis</a>
                                </td>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/DeliverableUnit2SWOTAnalysis.pdf">SWOT Analysis</a>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/Unit3RequirementsERD.pdf">Entity Relationship Diagram</a>
                                </td>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/DeliverableUnit3ERD.pdf">Entity Relationship Diagram</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>



        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <p style="margin-top:40px">Database creation narrows the class focus to four key business processes:</p>
                <ul style="list-style:none; margin-top:-16px; padding-left:0px">
                    <li>Customer Maintenance</li>
                    <li>Employee & Inventory Maintenance</li>
                    <li>Inventory & Sales Transactions</li>
                    <li>Reports</li>
                </ul>
                <p style="margin-bottom:0px">Application development and documentation proceeds through the remainder of the semester, with each of the key areas being developed. Microsoft Access 2016 and Visual Studio 2012 were used in the creation of the C# Winforms-based application.</p>
            </div>
        </div>



        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div style="padding:10px; border:2px solid #009999; background-color:rgba(0,153,153,0.05)">
                    <table id="capstoneTable" class="table-striped table-hover" style="width:100%">

                        <thead>
                            <tr>
                                <th style="padding:6px !important">
                                    Deliverable Instructions
                                </th>
                                <th style="padding:6px !important">
                                    Resulting Documentation
                                </th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/Unit4RequirementsDatabase.pdf">Initial Database creation</a>
                                </td>
                                <td style="padding:6px !important">
                                    <span>-</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/Unit5RequirementsDatabaseConnections.pdf">Application creation & Database connection</a>
                                </td>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/DeliverableUnit5DatabaseConnections.pdf">Database connection documentation</a>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/Unit6RequirementsCustomers.pdf">Customer Maintenance</a>
                                </td>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/DeliverableUnit6Customers.pdf">Customer Maintenance documentation</a>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/Unit7RequirementsEmployeesAndInventory.pdf">Employee and Inventory Maintenance</a>
                                </td>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/DeliverableUnit7EmployeesAndInventory.pdf">Employee and Inventory Maintenance documentation</a>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/Unit8RequirementsTransactions.pdf">Inventory & Sales Transactions</a>
                                </td>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/DeliverableUnit8Transactions.pdf">Transactions documentation</a>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/Unit9RequirementsReports.pdf">Reports</a>
                                </td>
                                <td style="padding:6px !important">
                                    <a href="~/Assets/pdf/DeliverableUnit9Reports.pdf">Reports documentation</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

    <div style="margin-top:10px">&nbsp;</div>
    <hr class="blue" />
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 text-center">
                <a href="@Url.Action("Portfolio","Home")" style="color:rgb(30, 80, 150)">Back to Portfolio</a>
            </div>
        </div>
    </div>
</section>

jritchie-portfolio/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


    <header class="masthead" style="margin-top:52px">
        <div class="header-content">
            <div class="header-content-inner">
                <h1 class="focus-in-contract-bck" id="homeHeading">John Ritchie</h1>
                <h2>Full-Stack Developer</h2>
                <hr>
                <p>Welcome!</p>
            </div>
        </div>
    </header>

jritchie-portfolio/Views/Home/Portfolio.cshtml
@{
    ViewBag.Title = "Portfolio";
}

<section id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading" style="text-shadow:2px 2px 3px rgba(30,30,30,0.25)">Portfolio</h2>
                <hr class="blue">
            </div>
        </div>
    </div>
    
    <!-- Coder Foundry projects -->
    <div class="container">

        <div class="col-lg-12 col-md-12 col-sm-12">
            <p style="text-align:center; color:rgb(30,80,150)">Work completed at Coder Foundry</p>
        </div>

        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 text-center">
                <div class="portfolio-box">
                    <a href="@Url.Action("Index", "JsExercises")" data-toggle="popover" data-trigger="hover" data-placement="top" title="Tech used:" data-content="Javascript, HTML, CSS, Bootstrap">
                        <i class="fa fa-4x fa-diamond text-primary sr-icons"></i>
                        <h3>Javascript Exercises</h3>
                        <p class="text-muted">Let these small gems catch your eye.</p>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 text-center">
                <div class="portfolio-box">
                    <a href="http://jritchie-shopping.azurewebsites.net/" data-toggle="popover" data-trigger="hover" data-placement="top" title="Tech used:" data-content="MVC Design pattern. HTML, CSS, Bootstrap, jQuery, TinyMCE jQuery plugin, C#, SQL, LINQ">
                        <i class="fa fa-4x fa-shopping-cart text-primary sr-icons"></i>
                        <h3>Shopping App</h3>
                        <p class="text-muted">Psst! Wanna buy a watch?</p>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 text-center">
                <div class="portfolio-box">
                    <a href="http://jritchie-blog.azurewebsites.net/" data-toggle="popover" data-trigger="hover" data-placement="top" title="Tech used:" data-content="MVC Design pattern. HTML, CSS, Bootstrap, jQuery, TinyMCE jQuery plugin, C#, SQL, LINQ, Blog slugs, PagedList.MVC, SMTP, 3rd-party login APIs">
                        <i class="fa fa-4x fa-book text-primary sr-icons"></i>
                        <h3>Blog</h3>
                        <p class="text-muted">Life at Coder Foundry.</p>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 text-center">
                <div class="portfolio-box">
                    <a href="https://jritchie-bugtracker.azurewebsites.net/" data-toggle="popover" data-trigger="hover" data-placement="top" title="Tech used:" data-content="MVC Design pattern. HTML, CSS, Bootstrap, jQuery, C#, SQL, LINQ">
                        <i class="fa fa-4x fa-bug text-primary sr-icons"></i>
                        <h3>Resolve()</h3>
                        <p class="text-muted">Issue Management Software</p>
                        <p>AKA "Bug Tracker"</p>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 text-center">
                <div class="portfolio-box">
                    <a href="https://jritchie-budgeter.azurewebsites.net/" data-toggle="popover" data-trigger="hover" data-placement="top" title="Tech used:" data-content="MVC Design pattern. HTML, CSS, Bootstrap, jQuery, C#, SQL, LINQ">
                        <i class="fa fa-4x fa-money text-primary sr-icons"></i>
                        <h3>Financial Portal</h3>
                        <p class="text-muted">Manage your personal finances.</p>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 text-center">
                <div class="portfolio-box">
                    <a href="https://jritchie-carapi.azurewebsites.net/" data-toggle="popover" data-trigger="hover" data-placement="top" title="Tech used:" data-content="MVC pattern. HTML, CSS, Bootstrap, jQuery, C#, SQL, LINQ, Web APIs, Database-first development, SwaggerAPI Project Documentation">
                        <i class="fa fa-4x fa-car text-primary sr-icons"></i>
                        <h3>NHTSA Car Recall Finder</h3>
                        <p class="text-muted">How safe is your car?</p>
                        <p>Web API</p>
                    </a>
                </div>
            </div>
        </div>
    </div>


    <!-- GTCC Coursework -->
    <hr class="blue" style="margin-top:60px" />
    <div class="container-fluid">

        <div class="col-lg-12 col-md-12 col-sm-12">
            <p style="text-align:center; color:rgb(30,80,150)">GTCC Coursework</p>
        </div>

        <div class="row">
            <div class="col-md-12 text-center">
                <div class="portfolio-box">
                    <a href="@Url.Action("GTCCCapstone", "Home")" data-toggle="popover" data-trigger="hover" data-placement="top" title="Tech used:" data-content="C#, WinForms, Microsoft Access, SQL">
                        <img src="~/Assets/img/portfolio/fullsize/GTCCLogo.jpg" class="sr-icons" style="height:60%; border:2px solid #009999; padding:8px" />
                        <h3>Degee coursework</h3>
                        <p class="text-muted">Business-case analysis & App Development</p>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <!-- Personal work -->
    <hr class="blue" style="margin-top:60px" />
    <div class="container-fluid">

        <div class="col-lg-12 col-md-12 col-sm-12">
            <p style="text-align:center; color:rgb(30,80,150)">Personal Work</p>
        </div>

        <div class="row">
            <div class="col-md-12 text-center">
                <div class="portfolio-box">
                    <a href="@Url.Action("TabPrinter", "Home")" data-toggle="popover" data-trigger="hover" data-placement="top" title="Tech used:" data-content="VB.NET, WinForms, Microsoft Access">
                        <img src="~/Assets/img/portfolio/fullsize/TabPrinter.jpg" class="sr-icons" style="height:60%; border:2px solid #009999; padding:8px" />
                        <h3>Tab Printer</h3>
                        <p class="text-muted">Used in a production environment</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
    

    <!-- GitHub -->
    <div style="margin-top:10px">&nbsp;</div>
    <hr class="blue" />
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="portfolio-box">
                    <a href="https://github.com/jwritchie/">
                        <i class="fa fa-4x fa-github text-primary sr-icons" style="color:black !important"></i>
                        <h3>GitHub</h3>
                        <p class="text-muted">Find my work on GitHub.</p>
                    </a>
                </div>
            </div>
        </div>
    </div>

</section>


@section scripts{
<script>
        $('[data-toggle="popover"]').popover();
</script>
}